services:
  adminer:
    profiles: ["local", "dev"]
    image: adminer:5.4.1
    container_name: musmgr-adminer
    networks:
      - musmgr
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - ${ADMINER_PORT:-8080}:8080

  minio:
    profiles: ["local", "dev"]
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - musmgr
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  postgres:
    profiles: ["local", "dev"]
    image: postgres:18.1
    container_name: musmgr-db
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - musmgr
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-musmgr}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  frontend-admin:
    profiles: ["dev"]
    build:
      context: ./frontend
    container_name: musmgr-frontend-admin
    environment:
      API_URL: http://go-gin:4700
      VITE_FRONTEND_BUILD_MODE: admin
    ports:
      - 3000:3000
    networks:
      - musmgr

  frontend-public:
    profiles: ["dev"]
    build:
      context: ./frontend
    container_name: musmgr-frontend-public
    environment:
      API_URL: http://go-gin:4701
      VITE_FRONTEND_BUILD_MODE: public
    ports:
      - 3001:3000
    networks:
      - musmgr

  go-gin:
    profiles: ["local", "dev"]
    build:
      context: ./backend
    container_name: musmgr-backend
    command: /app/main --storage-type MINIO
    ports:
      - ${ADMIN_PORT:-4700}:4700
      - ${PUBLIC_PORT:-4701}:4701
    environment:
      LOCAL_PATH: ${LOCAL_PATH:-minio_data}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:-default-bucket}
      MINIO_BUCKET_REGION: ${MINIO_BUCKET_REGION:-us-east-1}
      MINIO_SSL: ${MINIO_SSL:-false}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      ALLOWED_ADMIN_DOMAINS: ${ALLOWED_ADMIN_DOMAINS:-'["localhost"]'}
      ALLOWED_PUBLIC_DOMAINS: ${ALLOWED_PUBLIC_DOMAINS:-'["localhost"]'}
      DEPLOYMENT_TYPE: ${DEPLOYENT_TYPE:-DEVELOPMENT}
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    networks:
      - musmgr

networks:
  musmgr:
    driver: bridge

volumes:
  minio_data:
