# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.24)
{

  description = "MusMGR is a compositions manager that leverages the easiness of finding a composer's works related files and events";

  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/*";
  };

  outputs =
    {
      flake-schemas,
      nixpkgs,
      ...
    }:
    let

      supportedSystems = [ "x86_64-linux" ];
      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f {
            pkgs = import nixpkgs { inherit system; };
          }
        );
    in
    {

      schemas = flake-schemas.schemas;

      devShells = forEachSupportedSystem (
        { pkgs }:
        {
          default = pkgs.mkShell {

            packages = with pkgs; [
              biome
              curl
              git
              go
              jq
              nixpkgs-fmt
              pnpm
              sqlc
            ];
          };
        }
      );
    };
}
