---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

dotenv: [".env"]

vars:
  POSTGRES_URL: "postgres://{{.POSTGRES_USER}}:{{.POSTGRES_PASSWORD}}@{{.POSTGRES_HOST}}:5432/{{.POSTGRES_DB}}"

tasks:
  install-deps:
    cmds:
      - echo "Installing dependencies..."
      - cd backend && go mod download
      - cd frontend && pnpm install

  start-containers:
    vars:
      STAGE: "{{.STAGE}}"
    cmds:
      - echo "Starting Docker containers..."
      - docker compose --profile {{.STAGE}} up

  build-containers:
    vars:
      STAGE: "{{.STAGE}}"
    cmds:
      - echo "Building Docker containers..."
      - docker compose --profile {{.STAGE}} build

  stop-containers:
    vars:
      STAGE: "{{.STAGE}}"
    cmds:
      - echo "Stopping Docker containers..."
      - docker compose --profile {{.STAGE}} down

  backend:lint:
    cmds:
      - cd backend && go vet ./...

  backend:format:
    cmds:
      - cd backend && gofmt -w .

  db:create-migration:
    vars:
      NAME: "{{.NAME}}"
    cmds:
      - |
        echo Creating new migration: {{ .NAME }}
      - cd backend && goose -dir db/migrations postgres {{.POSTGRES_URL}} create {{.NAME}} sql

  db:migrate:
    cmds:
      - echo "Running database migrations..."
      - cd backend && goose -dir db/migrations postgres {{.POSTGRES_URL}} up

  db:dump-schema:
    cmds:
      - echo "Dumping database to schema.sql..."
      - |
        pg_dump \
        -s \
        --format=plain \
        --no-owner \
        --no-privileges \
        -h {{.POSTGRES_HOST}} \
        -U {{.POSTGRES_USER}} \
        {{.POSTGRES_DB}} \
        --exclude-table=public.goose_db_version \
        | sed '/^\\restrict/d; /^\\unrestrict/d' \
        > backend/db/schema.sql

  db:create-models:
    cmds:
      - echo "Creating controllers from schema..."
      - cd backend/db && sqlc generate

  db:populate:
    cmds:
      - echo "Populating database using fixtures..."
      - cd backend && go run cmd/populate/main.go

  frontend:admin-dev:
    cmds:
      - echo "Starting frontend server..."
      - cd frontend && pnpm dev:admin

  frontend:dev:
    vars:
      MODE: "{{.MODE}}"
      API_URL: "{{.API_URL}}"
    cmds:
      - cd frontend && API_URL={{.API_URL}} pnpm dev:{{.MODE}}

  frontend:lint:
    cmds:
      - cd frontend && pnpm biome lint .

  frontend:format:
    cmds:
      - cd frontend && pnpm biome format --write .
