// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package model

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :exec
insert into musmgr.events (id, happened_at, description, event_type, create_at, updated_at)
values ($1, $2, $3, $4, now(), now())
`

type CreateEventParams struct {
	ID          uuid.UUID       `json:"id"`
	HappenedAt  pgtype.Date     `json:"happened_at"`
	Description pgtype.Text     `json:"description"`
	EventType   MusmgrEventType `json:"event_type"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.ID,
		arg.HappenedAt,
		arg.Description,
		arg.EventType,
	)
	return err
}

const createFile = `-- name: CreateFile :exec
insert into musmgr.files (id, name, piece_id, create_at, updated_at)
values ($1, $2, $3, now(), now())
`

type CreateFileParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	PieceID uuid.UUID `json:"piece_id"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.Exec(ctx, createFile, arg.ID, arg.Name, arg.PieceID)
	return err
}

const createPiece = `-- name: CreatePiece :exec
insert into musmgr.pieces (id, composed_at, instrumentation, title, create_at, updated_at)
values ($1, $2, $3, $4, now(), now())
`

type CreatePieceParams struct {
	ID              uuid.UUID                 `json:"id"`
	ComposedAt      pgtype.Date               `json:"composed_at"`
	Instrumentation MusmgrInstrumentationName `json:"instrumentation"`
	Title           string                    `json:"title"`
}

func (q *Queries) CreatePiece(ctx context.Context, arg CreatePieceParams) error {
	_, err := q.db.Exec(ctx, createPiece,
		arg.ID,
		arg.ComposedAt,
		arg.Instrumentation,
		arg.Title,
	)
	return err
}

const createPieceEvent = `-- name: CreatePieceEvent :exec
insert into musmgr.pieces_events (piece_id, event_id)
values ($1, $2)
`

type CreatePieceEventParams struct {
	PieceID uuid.UUID `json:"piece_id"`
	EventID uuid.UUID `json:"event_id"`
}

func (q *Queries) CreatePieceEvent(ctx context.Context, arg CreatePieceEventParams) error {
	_, err := q.db.Exec(ctx, createPieceEvent, arg.PieceID, arg.EventID)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
delete from musmgr.events
where id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
delete from musmgr.files
where id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const deletePiece = `-- name: DeletePiece :exec
delete from musmgr.pieces
where id = $1
`

func (q *Queries) DeletePiece(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePiece, id)
	return err
}

const deletePieceEvent = `-- name: DeletePieceEvent :exec
delete from musmgr.pieces_events
where piece_id = $1 and event_id = $2
`

type DeletePieceEventParams struct {
	PieceID uuid.UUID `json:"piece_id"`
	EventID uuid.UUID `json:"event_id"`
}

func (q *Queries) DeletePieceEvent(ctx context.Context, arg DeletePieceEventParams) error {
	_, err := q.db.Exec(ctx, deletePieceEvent, arg.PieceID, arg.EventID)
	return err
}

const getEventPieces = `-- name: GetEventPieces :many
select id, composed_at, instrumentation, title from musmgr.pieces
inner join musmgr.pieces_events
on musmgr.pieces.id = musmgr.pieces_events.piece_id
where musmgr.pieces.id = $1
`

type GetEventPiecesRow struct {
	ID              uuid.UUID                 `json:"id"`
	ComposedAt      pgtype.Date               `json:"composed_at"`
	Instrumentation MusmgrInstrumentationName `json:"instrumentation"`
	Title           string                    `json:"title"`
}

func (q *Queries) GetEventPieces(ctx context.Context, id uuid.UUID) ([]GetEventPiecesRow, error) {
	rows, err := q.db.Query(ctx, getEventPieces, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventPiecesRow
	for rows.Next() {
		var i GetEventPiecesRow
		if err := rows.Scan(
			&i.ID,
			&i.ComposedAt,
			&i.Instrumentation,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventTypeEvents = `-- name: GetEventTypeEvents :many
select id, happened_at, happened_at_precision, description, event_type, created_at, uphappened_atd_at from musmgr.events
where event_type = $1
`

func (q *Queries) GetEventTypeEvents(ctx context.Context, eventType MusmgrEventType) ([]MusmgrEvent, error) {
	rows, err := q.db.Query(ctx, getEventTypeEvents, eventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusmgrEvent
	for rows.Next() {
		var i MusmgrEvent
		if err := rows.Scan(
			&i.ID,
			&i.HappenedAt,
			&i.HappenedAtPrecision,
			&i.Description,
			&i.EventType,
			&i.CreatedAt,
			&i.UphappenedAtdAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvents = `-- name: GetEvents :many
select id, happened_at, happened_at_precision, description, event_type, created_at, uphappened_atd_at from musmgr.events
`

func (q *Queries) GetEvents(ctx context.Context) ([]MusmgrEvent, error) {
	rows, err := q.db.Query(ctx, getEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusmgrEvent
	for rows.Next() {
		var i MusmgrEvent
		if err := rows.Scan(
			&i.ID,
			&i.HappenedAt,
			&i.HappenedAtPrecision,
			&i.Description,
			&i.EventType,
			&i.CreatedAt,
			&i.UphappenedAtdAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstrumentationPieces = `-- name: GetInstrumentationPieces :many
select id, composed_at, composed_at_precision, instrumentation, title, created_at, updated_at from musmgr.pieces
where instrumentation = $1
`

func (q *Queries) GetInstrumentationPieces(ctx context.Context, instrumentation MusmgrInstrumentationName) ([]MusmgrPiece, error) {
	rows, err := q.db.Query(ctx, getInstrumentationPieces, instrumentation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusmgrPiece
	for rows.Next() {
		var i MusmgrPiece
		if err := rows.Scan(
			&i.ID,
			&i.ComposedAt,
			&i.ComposedAtPrecision,
			&i.Instrumentation,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPieceEvents = `-- name: GetPieceEvents :many
select id, happened_at, description, event_type from musmgr.events
inner join musmgr.pieces_events
on musmgr.events.id = musmgr.pieces_events.event_id
where musmgr.pieces_events.piece_id = $1
`

type GetPieceEventsRow struct {
	ID          uuid.UUID       `json:"id"`
	HappenedAt  pgtype.Date     `json:"happened_at"`
	Description pgtype.Text     `json:"description"`
	EventType   MusmgrEventType `json:"event_type"`
}

func (q *Queries) GetPieceEvents(ctx context.Context, pieceID uuid.UUID) ([]GetPieceEventsRow, error) {
	rows, err := q.db.Query(ctx, getPieceEvents, pieceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPieceEventsRow
	for rows.Next() {
		var i GetPieceEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.HappenedAt,
			&i.Description,
			&i.EventType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPieceFiles = `-- name: GetPieceFiles :many
select id, name, piece_id, created_at, updated_at from musmgr.files
where piece_id = $1
`

func (q *Queries) GetPieceFiles(ctx context.Context, pieceID uuid.UUID) ([]MusmgrFile, error) {
	rows, err := q.db.Query(ctx, getPieceFiles, pieceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusmgrFile
	for rows.Next() {
		var i MusmgrFile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PieceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPieces = `-- name: GetPieces :many
select id, composed_at, composed_at_precision, instrumentation, title, created_at, updated_at from musmgr.pieces
`

func (q *Queries) GetPieces(ctx context.Context) ([]MusmgrPiece, error) {
	rows, err := q.db.Query(ctx, getPieces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusmgrPiece
	for rows.Next() {
		var i MusmgrPiece
		if err := rows.Scan(
			&i.ID,
			&i.ComposedAt,
			&i.ComposedAtPrecision,
			&i.Instrumentation,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :exec
update musmgr.events
set happened_at = coalesce($2, happened_at),
    description = coalesce($3, description),
    event_type = coalesce($4, event_type),
    updated_at = now()
where id = $1
`

type UpdateEventParams struct {
	ID          uuid.UUID           `json:"id"`
	HappenedAt  pgtype.Date         `json:"happened_at"`
	Description pgtype.Text         `json:"description"`
	EventType   NullMusmgrEventType `json:"event_type"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.Exec(ctx, updateEvent,
		arg.ID,
		arg.HappenedAt,
		arg.Description,
		arg.EventType,
	)
	return err
}

const updateFile = `-- name: UpdateFile :exec
update musmgr.files
set name = coalesce($2, name),
    updated_at = now()
where id = $1
`

type UpdateFileParams struct {
	ID   uuid.UUID   `json:"id"`
	Name pgtype.Text `json:"name"`
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) error {
	_, err := q.db.Exec(ctx, updateFile, arg.ID, arg.Name)
	return err
}

const updatePiece = `-- name: UpdatePiece :exec
update musmgr.pieces
set composed_at = coalesce($2, composed_at),
    instrumentation = coalesce($3, instrumentation),
    title = coalesce($4, title),
    updated_at = now()
where id = $1
`

type UpdatePieceParams struct {
	ID              uuid.UUID                     `json:"id"`
	ComposedAt      pgtype.Date                   `json:"composed_at"`
	Instrumentation NullMusmgrInstrumentationName `json:"instrumentation"`
	Title           pgtype.Text                   `json:"title"`
}

func (q *Queries) UpdatePiece(ctx context.Context, arg UpdatePieceParams) error {
	_, err := q.db.Exec(ctx, updatePiece,
		arg.ID,
		arg.ComposedAt,
		arg.Instrumentation,
		arg.Title,
	)
	return err
}
