// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package model

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :exec
insert into musmgr.events (id, date, description, event_type, create_at, updated_at)
values ($1, $2, $3, $4, now(), now())
`

type CreateEventParams struct {
	ID          string          `json:"id"`
	Date        pgtype.Date     `json:"date"`
	Description pgtype.Text     `json:"description"`
	EventType   MusmgrEventType `json:"event_type"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.ID,
		arg.Date,
		arg.Description,
		arg.EventType,
	)
	return err
}

const createFile = `-- name: CreateFile :exec
insert into musmgr.files (id, name, work_id, create_at, updated_at)
values ($1, $2, $3, now(), now())
`

type CreateFileParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	WorkID string `json:"work_id"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.Exec(ctx, createFile, arg.ID, arg.Name, arg.WorkID)
	return err
}

const createWork = `-- name: CreateWork :exec
insert into musmgr.works (id, composed_at, instrumentation, title, create_at, updated_at)
values ($1, $2, $3, $4, now(), now())
`

type CreateWorkParams struct {
	ID              string                    `json:"id"`
	ComposedAt      pgtype.Date               `json:"composed_at"`
	Instrumentation MusmgrInstrumentationName `json:"instrumentation"`
	Title           string                    `json:"title"`
}

func (q *Queries) CreateWork(ctx context.Context, arg CreateWorkParams) error {
	_, err := q.db.Exec(ctx, createWork,
		arg.ID,
		arg.ComposedAt,
		arg.Instrumentation,
		arg.Title,
	)
	return err
}

const createWorkEvent = `-- name: CreateWorkEvent :exec
insert into musmgr.works_events (work_id, event_id)
values ($1, $2)
`

type CreateWorkEventParams struct {
	WorkID  string `json:"work_id"`
	EventID string `json:"event_id"`
}

func (q *Queries) CreateWorkEvent(ctx context.Context, arg CreateWorkEventParams) error {
	_, err := q.db.Exec(ctx, createWorkEvent, arg.WorkID, arg.EventID)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
delete from musmgr.events
where id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
delete from musmgr.files
where id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const deleteWork = `-- name: DeleteWork :exec
delete from musmgr.works
where id = $1
`

func (q *Queries) DeleteWork(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteWork, id)
	return err
}

const deleteWorkEvent = `-- name: DeleteWorkEvent :exec
delete from musmgr.works_events
where work_id = $1 and event_id = $2
`

type DeleteWorkEventParams struct {
	WorkID  string `json:"work_id"`
	EventID string `json:"event_id"`
}

func (q *Queries) DeleteWorkEvent(ctx context.Context, arg DeleteWorkEventParams) error {
	_, err := q.db.Exec(ctx, deleteWorkEvent, arg.WorkID, arg.EventID)
	return err
}

const getEventTypeEvents = `-- name: GetEventTypeEvents :many
select id, date, description, event_type from musmgr.events
where event_type = $1
`

func (q *Queries) GetEventTypeEvents(ctx context.Context, eventType MusmgrEventType) ([]MusmgrEvent, error) {
	rows, err := q.db.Query(ctx, getEventTypeEvents, eventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusmgrEvent
	for rows.Next() {
		var i MusmgrEvent
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.EventType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventWorks = `-- name: GetEventWorks :many
select id, composed_at, instrumentation, title from musmgr.works
inner join musmgr.works_events
on musmgr.works.id = musmgr.works_events.work_id
where musmgr.works.id = $1
`

func (q *Queries) GetEventWorks(ctx context.Context, id string) ([]MusmgrWork, error) {
	rows, err := q.db.Query(ctx, getEventWorks, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusmgrWork
	for rows.Next() {
		var i MusmgrWork
		if err := rows.Scan(
			&i.ID,
			&i.ComposedAt,
			&i.Instrumentation,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvents = `-- name: GetEvents :many
select id, date, description, event_type from musmgr.events
`

func (q *Queries) GetEvents(ctx context.Context) ([]MusmgrEvent, error) {
	rows, err := q.db.Query(ctx, getEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusmgrEvent
	for rows.Next() {
		var i MusmgrEvent
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.EventType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstrumentationWorks = `-- name: GetInstrumentationWorks :many
select id, composed_at, instrumentation, title from musmgr.works
where instrumentation = $1
`

func (q *Queries) GetInstrumentationWorks(ctx context.Context, instrumentation MusmgrInstrumentationName) ([]MusmgrWork, error) {
	rows, err := q.db.Query(ctx, getInstrumentationWorks, instrumentation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusmgrWork
	for rows.Next() {
		var i MusmgrWork
		if err := rows.Scan(
			&i.ID,
			&i.ComposedAt,
			&i.Instrumentation,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkEvents = `-- name: GetWorkEvents :many
select id, date, description, event_type from musmgr.events
inner join musmgr.works_events
on musmgr.events.id = musmgr.works_events.event_id
where musmgr.works_events.work_id = $1
`

func (q *Queries) GetWorkEvents(ctx context.Context, workID string) ([]MusmgrEvent, error) {
	rows, err := q.db.Query(ctx, getWorkEvents, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusmgrEvent
	for rows.Next() {
		var i MusmgrEvent
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.EventType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkFiles = `-- name: GetWorkFiles :many
select id, name, work_id from musmgr.files
where work_id = $1
`

func (q *Queries) GetWorkFiles(ctx context.Context, workID string) ([]MusmgrFile, error) {
	rows, err := q.db.Query(ctx, getWorkFiles, workID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusmgrFile
	for rows.Next() {
		var i MusmgrFile
		if err := rows.Scan(&i.ID, &i.Name, &i.WorkID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorks = `-- name: GetWorks :many
select id, composed_at, instrumentation, title from musmgr.works
`

func (q *Queries) GetWorks(ctx context.Context) ([]MusmgrWork, error) {
	rows, err := q.db.Query(ctx, getWorks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusmgrWork
	for rows.Next() {
		var i MusmgrWork
		if err := rows.Scan(
			&i.ID,
			&i.ComposedAt,
			&i.Instrumentation,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :exec
update musmgr.events
set date = coalesce($2, date),
    description = coalesce($3, description),
    event_type = coalesce($4, event_type),
    updated_at = now()
where id = $1
`

type UpdateEventParams struct {
	ID          string              `json:"id"`
	Date        pgtype.Date         `json:"date"`
	Description pgtype.Text         `json:"description"`
	EventType   NullMusmgrEventType `json:"event_type"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.Exec(ctx, updateEvent,
		arg.ID,
		arg.Date,
		arg.Description,
		arg.EventType,
	)
	return err
}

const updateFile = `-- name: UpdateFile :exec
update musmgr.files
set name = coalesce($2, name),
    updated_at = now()
where id = $1
`

type UpdateFileParams struct {
	ID   string      `json:"id"`
	Name pgtype.Text `json:"name"`
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) error {
	_, err := q.db.Exec(ctx, updateFile, arg.ID, arg.Name)
	return err
}

const updateWork = `-- name: UpdateWork :exec
update musmgr.works
set composed_at = coalesce($2, composed_at),
    instrumentation = coalesce($3, instrumentation),
    title = coalesce($4, title),
    updated_at = now()
where id = $1
`

type UpdateWorkParams struct {
	ID              string                        `json:"id"`
	ComposedAt      pgtype.Date                   `json:"composed_at"`
	Instrumentation NullMusmgrInstrumentationName `json:"instrumentation"`
	Title           pgtype.Text                   `json:"title"`
}

func (q *Queries) UpdateWork(ctx context.Context, arg UpdateWorkParams) error {
	_, err := q.db.Exec(ctx, updateWork,
		arg.ID,
		arg.ComposedAt,
		arg.Instrumentation,
		arg.Title,
	)
	return err
}
