// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package model

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EventTypeName string

const (
	EventTypeNameConcert     EventTypeName = "concert"
	EventTypeNameExibition   EventTypeName = "exibition"
	EventTypeNameCompetition EventTypeName = "competition"
	EventTypeNameFestival    EventTypeName = "festival"
	EventTypeNameOther       EventTypeName = "other"
)

func (e *EventTypeName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventTypeName(s)
	case string:
		*e = EventTypeName(s)
	default:
		return fmt.Errorf("unsupported scan type for EventTypeName: %T", src)
	}
	return nil
}

type NullEventTypeName struct {
	EventTypeName EventTypeName `json:"event_type_name"`
	Valid         bool          `json:"valid"` // Valid is true if EventTypeName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventTypeName) Scan(value interface{}) error {
	if value == nil {
		ns.EventTypeName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventTypeName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventTypeName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventTypeName), nil
}

type InstrumentationName string

const (
	InstrumentationNameChoir     InstrumentationName = "choir"
	InstrumentationNameSolo      InstrumentationName = "solo"
	InstrumentationNameChamber   InstrumentationName = "chamber"
	InstrumentationNameOrchestra InstrumentationName = "orchestra"
	InstrumentationNameOpera     InstrumentationName = "opera"
	InstrumentationNameMusical   InstrumentationName = "musical"
	InstrumentationNameAcusmatic InstrumentationName = "acusmatic"
)

func (e *InstrumentationName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InstrumentationName(s)
	case string:
		*e = InstrumentationName(s)
	default:
		return fmt.Errorf("unsupported scan type for InstrumentationName: %T", src)
	}
	return nil
}

type NullInstrumentationName struct {
	InstrumentationName InstrumentationName `json:"instrumentation_name"`
	Valid               bool                `json:"valid"` // Valid is true if InstrumentationName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInstrumentationName) Scan(value interface{}) error {
	if value == nil {
		ns.InstrumentationName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InstrumentationName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInstrumentationName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InstrumentationName), nil
}

type Event struct {
	ID          string      `json:"id"`
	Date        pgtype.Date `json:"date"`
	Description pgtype.Text `json:"description"`
	EventType   interface{} `json:"event_type"`
}

type File struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	FilePath string `json:"file_path"`
	WorkID   string `json:"work_id"`
}

type Work struct {
	ID              string              `json:"id"`
	ComposedAt      pgtype.Date         `json:"composed_at"`
	Instrumentation InstrumentationName `json:"instrumentation"`
	Title           string              `json:"title"`
}

type WorksEvent struct {
	WorkID  string `json:"work_id"`
	EventID string `json:"event_id"`
}
