// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package model

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FileType string

const (
	FileTypeText  FileType = "text"
	FileTypeScore FileType = "score"
	FileTypeSong  FileType = "song"
)

func (e *FileType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileType(s)
	case string:
		*e = FileType(s)
	default:
		return fmt.Errorf("unsupported scan type for FileType: %T", src)
	}
	return nil
}

type NullFileType struct {
	FileType FileType `json:"file_type"`
	Valid    bool     `json:"valid"` // Valid is true if FileType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileType) Scan(value interface{}) error {
	if value == nil {
		ns.FileType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileType), nil
}

type Category struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Event struct {
	ID          uuid.UUID   `json:"id"`
	EventDate   pgtype.Date `json:"event_date"`
	Description pgtype.Text `json:"description"`
	EventTypeID uuid.UUID   `json:"event_type_id"`
}

type EventType struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type File struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	FileContent []byte    `json:"file_content"`
	FileType    FileType  `json:"file_type"`
	SongID      uuid.UUID `json:"song_id"`
}

type Song struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	TonalityRoot    int32     `json:"tonality_root"`
	TonalityDetails string    `json:"tonality_details"`
	SubcategoryID   string    `json:"subcategory_id"`
}

type SongsEvent struct {
	SongID  uuid.UUID `json:"song_id"`
	EventID uuid.UUID `json:"event_id"`
}

type Subcategory struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	CategoryID uuid.UUID `json:"category_id"`
}
